=== Bedrock-OSS/regolith/schemas/config.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"type": "object",
	"description": "The root object of Regolith's config.json file",
	"properties": {
		"name": {
			"type": "string",
			"description": "The name of the project."
		},
		"author": {
			"type": "string",
			"description": "The author of the project."
		},
		"packs": {
			"type": "object",
			"description": "The paths to the source RP and BP files.",
			"properties": {
				"behaviorPack": {
					"type": "string",
					"description": "The path to the source behavior pack of the Regolith project."
				},
				"resourcePack": {
					"type": "string",
					"description": "The path to the source resource pack of the Regolith project."
				}
			}
		},
		"regolith": {
			"type": "object",
			"description": "The Regolith configuration object.",
			"properties": {
				"profiles": {
					"type": "object",
					"additionalProperties": {
						"type": "object",
						"properties": {
							"export": {
								"type": "object",
								"properties": {
									"readOnly": {
										"type": "boolean",
										"description": "Whether the RP and BP files generated by Regolith will be marked as read-only."
									},
									"target": {
										"type": "string",
										"description": "The type of the export target.",
										"enum": [
											"development",
											"preview",
											"local",
											"exact",
											"world"
										]
									},
									"rpPath": {
										"description": "The export resource pack path for the 'exact' export target.",
										"type": "string"
									},
									"bpPath": {
										"description": "The export behavior pack path for the 'exact' export target.",
										"type": "string"
									},
									"worldName": {
										"description": "The name of the world for exporting packs. Use only for the 'world' export target.",
										"type": "string"
									},
									"worldPath": {
										"description": "The path to the world for exporting packs. Use only for the 'world' export target.",
										"type": "string"
									}
								}
							},
							"filters": {
								"type": "array",
								"description": "The list of the filters used by the profile and their settigns.",
								"items": {
									"properties": {
										"disabled": {
											"type": "boolean",
											"description": "Whether the filter is disabled. The disabled filters are not applied, it's the same as if the filter was not specified in the profile."
										},
										"filter": {
											"type": "string",
											"description": "The name of the filter that matches one of the filter names from filterDefinitions."
										},
										"profile": {
											"type": "string",
											"description": "The name of another profile. Profiles can reference each other as long as the relation is not circular."
										},
										"settings": {
											"type": "object",
											"description": "The object with settings passed in JSON fromat to the filter as its first command line argument."
										},
										"arguments": {
											"type": "array",
											"description": "The list of the command line arguments passed to the filter. If combined with settings, the settings will be passed as the first argument and the rest of the arguments will be passet in later arguments.",
											"items": {
												"type": "string"
											}
										}
									},
									"additionalProperties": false,
									"required": ["filter"]
								}
							}
						},
						"additionalProperties": false
					}
				},
				"filterDefinitions": {
					"type": "object",
					"description": "The list of the filters installed for the project. This is mostly populated by Regolith itself with commands like 'regolith install'.",
					"additionalProperties": {
						"type": "object",
						"anyOf": [
							{
								"type": "object",
								"properties": {
									"url": {
										"type": "string",
										"description": "The URL to the reomte filter."
									},
									"version": {
										"type": "string",
										"description": "The version of the remote filter. It can be a commit ID on source repository, a tag, or a semantic version (which internally is converted to a tag using pattern: <filter-name>_<semver>."
									},
									"runWith": {
										"type": "string",
										"description": "The type of the filter.",
										"enum": [
											"java",
											"dotnet",
											"nim",
											"python",
											"shell",
											"nodejs",
											"deno",
											"exe"
										]
									},
									"command": {
										"type": "string",
										"description": "The command to run. Use only for 'shell' filters."
									},
									"script": {
										"type": "string",
										"description": "The path to the script - absolute or relative to the config.json file. Use only for the 'java', 'nim', 'python', 'nodejs' and 'deno' filters."
									},
									"exe": {
										"type": "string",
										"description": "The path to the executable - absolute or relative to the config.json file. Use only for the 'exe' filters."
									}
								},
								"additionalProperties": false
							}
						]
					}
				},
				"dataPath": {
					"type": "string",
					"description": "The path to the data folder of the Regolith filters."
				}
			}
		}
	},
	"additionalProperties": true
}

=== Bedrock-OSS/regolith/test/testdata/fresh_project/config.json
{
	"$schema": "https://raw.githubusercontent.com/Bedrock-OSS/regolith-schemas/main/config/unified.json",
	"author": "Your name",
	"name": "Project name",
	"packs": {
		"behaviorPack": "./packs/BP",
		"resourcePack": "./packs/RP"
	},
	"regolith": {
		"dataPath": "./packs/data",
		"filterDefinitions": {},
		"formatVersion": "1.8.0",
		"profiles": {
			"default": {
				"export": {
					"build": "standard",
					"readOnly": false,
					"target": "development"
				},
				"filters": []
			}
		}
	}
}

=== Bedrock-OSS/regolith/test/testdata/data_modify_remote_filter/project/config.json
{
	"$schema": "https://raw.githubusercontent.com/Bedrock-OSS/regolith-schemas/main/config/v1.1.json",
	"author": "Your name",
	"name": "Project name",
	"packs": {
		"behaviorPack": "./packs/BP",
		"resourcePack": "./packs/RP"
	},
	"regolith": {
		"dataPath": "./packs/data",
		"filterDefinitions": {
			"modify-data-filter": {
				"url": "github.com/Bedrock-OSS/regolith-test-filters",
				"version": "6230216184232e5bc7439caaf20cdd4c0dc17ca2"
			}
		},
		"profiles": {
			"default": {
				"export": {
					"readOnly": false,
					"target": "local"
				},
				"filters": [
					{
						"filter": "modify-data-filter"
					}
				]
			}
		}
	}
}

=== Bedrock-OSS/regolith/test/testdata/remote_manifest/1_start/config.json
{
	"$schema": "https://raw.githubusercontent.com/Bedrock-OSS/regolith-schemas/main/config/v1.4.json",
	"author": "Your name",
	"name": "Project name",
	"packs": {
		"behaviorPack": "./packs/BP",
		"resourcePack": "./packs/RP"
	},
	"regolith": {
		"dataPath": "./packs/data",
		"filterDefinitions": {},
		"formatVersion": "1.4.0",
		"profiles": {
			"default": {
				"export": {
					"target": "local"
				},
				"filters": []
			}
		}
	}
}

=== Bedrock-OSS/regolith/test/testdata/apply_filter/filtered_project/config.json
{
	"$schema": "https://raw.githubusercontent.com/Bedrock-OSS/regolith-schemas/main/config/v1.2.json",
	"author": "Your name",
	"name": "Project name",
	"packs": {
		"behaviorPack": "./packs/BP",
		"resourcePack": "./packs/RP"
	},
	"regolith": {
		"dataPath": "./packs/data",
		"filterDefinitions": {
			"test_filter": {
				"runWith": "python",
				"script": "local_filters/test_filter.py"
			}
		},
		"profiles": {
			"default": {
				"export": {
					"readOnly": false,
					"target": "development"
				},
				"filters": []
			}
		}
	}
}

=== Bedrock-OSS/regolith/test/testdata/double_remote_project/config.json
{
	"$schema": "https://raw.githubusercontent.com/Bedrock-OSS/regolith-schemas/main/config/v1.2.json",
	"name": "regolith_test_project",
	"author": "Bedrock-OSS",
	"packs": {
		"behaviorPack": "./packs/BP",
		"resourcePack": "./packs/RP"
	},
	"regolith": {
		"dataPath": "./packs/data",
		"filterDefinitions": {
			"nested-remote-filter": {
				"url": "github.com/Bedrock-OSS/regolith-test-filters",
				"version": "6230216184232e5bc7439caaf20cdd4c0dc17ca2"
			}
		},
		"profiles": {
			"dev": {
				"filters": [
					{
						"filter": "nested-remote-filter"
					}
				],
				"export": {
					"target": "development"
				}
			}
		}
	}
}

=== Bedrock-OSS/regolith/test/testdata/remote_manifest/config.json
{
	"$schema": "https://raw.githubusercontent.com/Bedrock-OSS/regolith-schemas/main/config/v1.2.json",
	"name": "regolith_test_project",
	"author": "Bedrock-OSS",
	"packs": {
		"behaviorPack": "./packs/BP",
		"resourcePack": "./packs/RP"
	},
	"regolith": {
		"profiles": {
			"default": {
				"filters": [],
				"export": {
					"target": "local"
				}
			}
		},
		"dataPath": "./packs/data",
		"filterDefinitions": {}
	}
}

=== Bedrock-OSS/regolith/test/testdata/size_time_check_optimization/project_after_run/config.json
{
	"$schema": "https://raw.githubusercontent.com/Bedrock-OSS/regolith-schemas/main/config/v1.2.json",
	"author": "Your name",
	"name": "Project name",
	"packs": {
		"behaviorPack": "./packs/BP",
		"resourcePack": "./packs/RP"
	},
	"regolith": {
		"dataPath": "./packs/data",
		"filterDefinitions": {
			"fill_with_data": {
				"runWith": "python",
				"script": "local_filters/fill_with_data.py"
			}
		},
		"profiles": {
			"default": {
				"export": {
					"readOnly": true,
					"target": "local",
					"bpName": "'BP'",
					"rpName": "'RP'"
				},
				"filters": [
					{
						"filter": "fill_with_data"
					}
				]
			}
		}
	}
}

=== Bedrock-OSS/regolith/test/testdata/remote_manifest_install_all/config.json
{
	"$schema": "https://raw.githubusercontent.com/Bedrock-OSS/regolith-schemas/main/config/v1.2.json",
	"author": "Bedrock-OSS",
	"name": "regolith_test_project",
	"packs": {
		"behaviorPack": "./packs/BP",
		"resourcePack": "./packs/RP"
	},
	"regolith": {
		"dataPath": "./packs/data",
		"filterDefinitions": {
			"my_release_filter": {
				"url": "github.com/akashic-records-of-the-abyss/basic_regolith",
				"version": "1.0.0"
			},
			"nested_filter": {
				"url": "github.com/akashic-records-of-the-abyss/basic_regolith",
				"version": "1.0.0"
			}
		},
		"profiles": {
			"default": {
				"export": {
					"target": "local"
				},
				"filters": [
					{
						"filter": "my_release_filter"
					},
					{
						"filter": "nested_filter"
					}
				]
			}
		}
	}
}
